import uuid

TRUCKS_SEED = [
    {
        "slug": "burger-truck",
        "name_de": "Burger Truck", "name_en": "Burger Truck", "name_fr": "Burger Truck", "name_it": "Burger Truck",
        "tagline_de": "Classic \u00b7 Chicken \u00b7 Veggie \u2014 bis 300 G\u00e4ste/h",
        "tagline_en": "Classic \u00b7 Chicken \u00b7 Veggie \u2014 up to 300 guests/h",
        "tagline_fr": "Classic \u00b7 Chicken \u00b7 Veggie \u2014 jusqu'\u00e0 300 invit\u00e9s/h",
        "tagline_it": "Classic \u00b7 Chicken \u00b7 Veggie \u2014 fino a 300 ospiti/h",
        "description_de": "Unser Burger Truck ist auf schnelle, hochwertige Ausgabe ausgelegt und ideal f\u00fcr Events mit hoher Besucherzahl. Saftige Patties, frische Zutaten und unser Signature-Style machen jeden Burger zu einem Erlebnis.",
        "description_en": "Our Burger Truck is designed for fast, high-quality service and is ideal for events with large crowds. Juicy patties, fresh ingredients, and our signature style make every burger an experience.",
        "description_fr": "Notre Burger Truck est con\u00e7u pour un service rapide et de haute qualit\u00e9, id\u00e9al pour les \u00e9v\u00e9nements \u00e0 forte affluence. Des steaks juteux, des ingr\u00e9dients frais et notre style signature font de chaque burger une exp\u00e9rience.",
        "description_it": "Il nostro Burger Truck \u00e8 progettato per un servizio rapido e di alta qualit\u00e0, ideale per eventi con grande affluenza. Polpette succose, ingredienti freschi e il nostro stile signature rendono ogni burger un'esperienza.",
        "image": "https://images.unsplash.com/photo-1565123409695-7b5ef63a2efb?w=1200&q=80",
        "tag": "Flagship",
        "menu_de": ["Classic Burger", "Chicken Burger", "Veggie Burger", "Loaded Fries"],
        "menu_en": ["Classic Burger", "Chicken Burger", "Veggie Burger", "Loaded Fries"],
        "menu_fr": ["Classic Burger", "Chicken Burger", "Veggie Burger", "Loaded Fries"],
        "menu_it": ["Classic Burger", "Chicken Burger", "Veggie Burger", "Loaded Fries"],
        "suitable_for_de": ["Festivals", "Firmenanl\u00e4sse", "Private Events", "Messen"],
        "suitable_for_en": ["Festivals", "Corporate Events", "Private Events", "Trade Fairs"],
        "suitable_for_fr": ["Festivals", "\u00c9v\u00e9nements d'entreprise", "\u00c9v\u00e9nements priv\u00e9s", "Salons"],
        "suitable_for_it": ["Festival", "Eventi aziendali", "Eventi privati", "Fiere"],
        "capacity": "bis 300 G\u00e4ste/h", "space_required": "6m x 3m", "power": "230V / 16A",
        "water": "Wasseranschluss ben\u00f6tigt", "setup_time": "ca. 60 Min",
        "is_wide": True, "is_active": True, "order": 1
    },
    {
        "slug": "chicken-burger-truck",
        "name_de": "Chicken Burger Truck", "name_en": "Chicken Burger Truck", "name_fr": "Chicken Burger Truck", "name_it": "Chicken Burger Truck",
        "tagline_de": "Knusprig \u00b7 W\u00fcrzig \u00b7 Einzigartig",
        "tagline_en": "Crispy \u00b7 Spicy \u00b7 Unique",
        "tagline_fr": "Croustillant \u00b7 \u00c9pic\u00e9 \u00b7 Unique",
        "tagline_it": "Croccante \u00b7 Piccante \u00b7 Unico",
        "description_de": "Unser Chicken Burger Truck bietet ein spezialisiertes Konzept rund um knusprige Chicken Burger mit hauseigenen Marinaden und frischen Saucen.",
        "description_en": "Our Chicken Burger Truck offers a specialized concept centered around crispy chicken burgers with house-made marinades and fresh sauces.",
        "description_fr": "Notre Chicken Burger Truck propose un concept sp\u00e9cialis\u00e9 autour de burgers au poulet croustillants avec des marinades maison et des sauces fra\u00eeches.",
        "description_it": "Il nostro Chicken Burger Truck offre un concetto specializzato incentrato su burger di pollo croccanti con marinature fatte in casa e salse fresche.",
        "image": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
        "tag": "",
        "menu_de": ["Classic Chicken Burger", "Spicy Chicken", "BBQ Chicken", "Veggie Alternative"],
        "menu_en": ["Classic Chicken Burger", "Spicy Chicken", "BBQ Chicken", "Veggie Alternative"],
        "menu_fr": ["Classic Chicken Burger", "Spicy Chicken", "BBQ Chicken", "Alternative v\u00e9g\u00e9tarienne"],
        "menu_it": ["Classic Chicken Burger", "Spicy Chicken", "BBQ Chicken", "Alternativa vegetariana"],
        "suitable_for_de": ["Festivals", "Firmenanl\u00e4sse", "Streetfood Events"],
        "suitable_for_en": ["Festivals", "Corporate Events", "Street Food Events"],
        "suitable_for_fr": ["Festivals", "\u00c9v\u00e9nements d'entreprise", "\u00c9v\u00e9nements street food"],
        "suitable_for_it": ["Festival", "Eventi aziendali", "Eventi street food"],
        "capacity": "bis 250 G\u00e4ste/h", "space_required": "5m x 3m", "power": "230V / 16A",
        "water": "Wasseranschluss ben\u00f6tigt", "setup_time": "ca. 45 Min",
        "is_wide": False, "is_active": True, "order": 2
    },
    {
        "slug": "bowl-truck",
        "name_de": "Bowl Truck", "name_en": "Bowl Truck", "name_fr": "Bowl Truck", "name_it": "Bowl Truck",
        "tagline_de": "Signature \u00b7 Protein \u00b7 Veggie",
        "tagline_en": "Signature \u00b7 Protein \u00b7 Veggie",
        "tagline_fr": "Signature \u00b7 Prot\u00e9ines \u00b7 V\u00e9g\u00e9tarien",
        "tagline_it": "Signature \u00b7 Proteine \u00b7 Veggie",
        "description_de": "Unser Bowl Truck liefert frische, gesunde Bowls mit saisonalen Zutaten. Ideal f\u00fcr gesundheitsbewusste G\u00e4ste und moderne Events.",
        "description_en": "Our Bowl Truck delivers fresh, healthy bowls with seasonal ingredients. Ideal for health-conscious guests and modern events.",
        "description_fr": "Notre Bowl Truck propose des bowls frais et sains avec des ingr\u00e9dients de saison. Id\u00e9al pour les invit\u00e9s soucieux de leur sant\u00e9 et les \u00e9v\u00e9nements modernes.",
        "description_it": "Il nostro Bowl Truck offre bowl freschi e sani con ingredienti di stagione. Ideale per ospiti attenti alla salute e eventi moderni.",
        "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
        "tag": "",
        "menu_de": ["Signature Bowl", "Protein Bowl", "Veggie Bowl", "Vegan Bowl"],
        "menu_en": ["Signature Bowl", "Protein Bowl", "Veggie Bowl", "Vegan Bowl"],
        "menu_fr": ["Signature Bowl", "Protein Bowl", "Veggie Bowl", "Vegan Bowl"],
        "menu_it": ["Signature Bowl", "Protein Bowl", "Veggie Bowl", "Vegan Bowl"],
        "suitable_for_de": ["Firmenanl\u00e4sse", "Messen", "Gesundheits-Events", "Private Events"],
        "suitable_for_en": ["Corporate Events", "Trade Fairs", "Health Events", "Private Events"],
        "suitable_for_fr": ["\u00c9v\u00e9nements d'entreprise", "Salons", "\u00c9v\u00e9nements sant\u00e9", "\u00c9v\u00e9nements priv\u00e9s"],
        "suitable_for_it": ["Eventi aziendali", "Fiere", "Eventi salute", "Eventi privati"],
        "capacity": "bis 200 G\u00e4ste/h", "space_required": "5m x 3m", "power": "230V / 16A",
        "water": "Wasseranschluss ben\u00f6tigt", "setup_time": "ca. 45 Min",
        "is_wide": False, "is_active": True, "order": 3
    },
    {
        "slug": "pocket-bowl-truck",
        "name_de": "Pocket Bowl Truck", "name_en": "Pocket Bowl Truck", "name_fr": "Pocket Bowl Truck", "name_it": "Pocket Bowl Truck",
        "tagline_de": "Ideal f\u00fcr hohe Frequenz",
        "tagline_en": "Ideal for high frequency",
        "tagline_fr": "Id\u00e9al pour les hautes fr\u00e9quences",
        "tagline_it": "Ideale per alta frequenza",
        "description_de": "Der Pocket Bowl Truck ist unser schnellstes Konzept. Kleine, handliche Bowls ideal f\u00fcr Events mit schnellem Durchlauf und hoher G\u00e4stefrequenz.",
        "description_en": "The Pocket Bowl Truck is our fastest concept. Small, handy bowls ideal for events with fast throughput and high guest frequency.",
        "description_fr": "Le Pocket Bowl Truck est notre concept le plus rapide. De petits bowls pratiques, id\u00e9aux pour les \u00e9v\u00e9nements \u00e0 d\u00e9bit rapide et haute fr\u00e9quentation.",
        "description_it": "Il Pocket Bowl Truck \u00e8 il nostro concetto pi\u00f9 veloce. Piccoli bowl pratici, ideali per eventi con flusso rapido e alta frequenza di ospiti.",
        "image": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80",
        "tag": "Speed",
        "menu_de": ["Pocket Bowl Classic", "Pocket Bowl Spicy", "Pocket Bowl Veggie"],
        "menu_en": ["Pocket Bowl Classic", "Pocket Bowl Spicy", "Pocket Bowl Veggie"],
        "menu_fr": ["Pocket Bowl Classic", "Pocket Bowl Spicy", "Pocket Bowl Veggie"],
        "menu_it": ["Pocket Bowl Classic", "Pocket Bowl Spicy", "Pocket Bowl Veggie"],
        "suitable_for_de": ["Festivals", "Grossevents", "Messen", "Sportanl\u00e4sse"],
        "suitable_for_en": ["Festivals", "Large Events", "Trade Fairs", "Sports Events"],
        "suitable_for_fr": ["Festivals", "Grands \u00e9v\u00e9nements", "Salons", "\u00c9v\u00e9nements sportifs"],
        "suitable_for_it": ["Festival", "Grandi eventi", "Fiere", "Eventi sportivi"],
        "capacity": "bis 400 G\u00e4ste/h", "space_required": "5m x 3m", "power": "230V / 16A",
        "water": "Wasseranschluss ben\u00f6tigt", "setup_time": "ca. 40 Min",
        "is_wide": False, "is_active": True, "order": 4
    },
    {
        "slug": "empanadas-truck",
        "name_de": "Empanadas Truck", "name_en": "Empanadas Truck", "name_fr": "Empanadas Truck", "name_it": "Empanadas Truck",
        "tagline_de": "Herzhaft \u00b7 Vegetarisch \u00b7 Schnell",
        "tagline_en": "Savory \u00b7 Vegetarian \u00b7 Fast",
        "tagline_fr": "Sal\u00e9 \u00b7 V\u00e9g\u00e9tarien \u00b7 Rapide",
        "tagline_it": "Salato \u00b7 Vegetariano \u00b7 Veloce",
        "description_de": "Unser Empanadas Truck bringt s\u00fcdamerikanisches Flair auf jedes Event. Handgemachte Empanadas in verschiedenen Sorten \u2013 herzhaft und vegetarisch.",
        "description_en": "Our Empanadas Truck brings South American flair to every event. Handmade empanadas in various flavors \u2013 savory and vegetarian.",
        "description_fr": "Notre Empanadas Truck apporte une touche sud-am\u00e9ricaine \u00e0 chaque \u00e9v\u00e9nement. Des empanadas faites main en plusieurs vari\u00e9t\u00e9s \u2013 sal\u00e9es et v\u00e9g\u00e9tariennes.",
        "description_it": "Il nostro Empanadas Truck porta il fascino sudamericano ad ogni evento. Empanadas fatte a mano in varie variet\u00e0 \u2013 salate e vegetariane.",
        "image": "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600&q=80",
        "tag": "",
        "menu_de": ["Classic Beef", "Chicken Empanada", "Veggie Empanada", "Cheese Empanada"],
        "menu_en": ["Classic Beef", "Chicken Empanada", "Veggie Empanada", "Cheese Empanada"],
        "menu_fr": ["Classic Beef", "Chicken Empanada", "Veggie Empanada", "Cheese Empanada"],
        "menu_it": ["Classic Beef", "Chicken Empanada", "Veggie Empanada", "Cheese Empanada"],
        "suitable_for_de": ["Festivals", "Private Events", "Streetfood M\u00e4rkte", "Firmenanl\u00e4sse"],
        "suitable_for_en": ["Festivals", "Private Events", "Street Food Markets", "Corporate Events"],
        "suitable_for_fr": ["Festivals", "\u00c9v\u00e9nements priv\u00e9s", "March\u00e9s street food", "\u00c9v\u00e9nements d'entreprise"],
        "suitable_for_it": ["Festival", "Eventi privati", "Mercati street food", "Eventi aziendali"],
        "capacity": "bis 300 G\u00e4ste/h", "space_required": "5m x 3m", "power": "230V / 16A",
        "water": "Wasseranschluss ben\u00f6tigt", "setup_time": "ca. 45 Min",
        "is_wide": False, "is_active": True, "order": 5
    },
    {
        "slug": "retro-trailer",
        "name_de": "Retro Trailer", "name_en": "Retro Trailer", "name_fr": "Retro Trailer", "name_it": "Retro Trailer",
        "tagline_de": "Pferdeanh\u00e4nger \u00b7 Vintage Charme",
        "tagline_en": "Horse Trailer \u00b7 Vintage Charm",
        "tagline_fr": "Remorque \u00b7 Charme Vintage",
        "tagline_it": "Rimorchio \u00b7 Fascino Vintage",
        "description_de": "Unser Retro Trailer im Pferdeanh\u00e4nger-Stil ist ein echter Hingucker. Perfekt f\u00fcr Hochzeiten, Privatanl\u00e4sse und \u00fcberall dort, wo Charme und Stil gefragt sind.",
        "description_en": "Our Retro Trailer in horse trailer style is a real eye-catcher. Perfect for weddings, private events, and wherever charm and style are needed.",
        "description_fr": "Notre Retro Trailer au style remorque est un v\u00e9ritable eye-catcher. Parfait pour les mariages, les \u00e9v\u00e9nements priv\u00e9s et partout o\u00f9 le charme et le style sont recherch\u00e9s.",
        "description_it": "Il nostro Retro Trailer in stile rimorchio \u00e8 un vero eye-catcher. Perfetto per matrimoni, eventi privati e ovunque si cerchi charme e stile.",
        "image": "https://images.unsplash.com/photo-1509315811345-672d83ef2fbc?w=600&q=80",
        "tag": "Retro",
        "menu_de": ["Individuell nach Absprache", "Kaffee & Desserts", "Alpine Spezialit\u00e4ten"],
        "menu_en": ["Customized by arrangement", "Coffee & Desserts", "Alpine Specialties"],
        "menu_fr": ["Personnalis\u00e9 sur demande", "Caf\u00e9 & Desserts", "Sp\u00e9cialit\u00e9s alpines"],
        "menu_it": ["Personalizzato su richiesta", "Caff\u00e8 & Dessert", "Specialit\u00e0 alpine"],
        "suitable_for_de": ["Hochzeiten", "Private Events", "Firmenfeiern", "M\u00e4rkte"],
        "suitable_for_en": ["Weddings", "Private Events", "Corporate Celebrations", "Markets"],
        "suitable_for_fr": ["Mariages", "\u00c9v\u00e9nements priv\u00e9s", "F\u00eates d'entreprise", "March\u00e9s"],
        "suitable_for_it": ["Matrimoni", "Eventi privati", "Feste aziendali", "Mercati"],
        "capacity": "bis 150 G\u00e4ste/h", "space_required": "4m x 2.5m", "power": "230V / 16A",
        "water": "Optional", "setup_time": "ca. 30 Min",
        "is_wide": False, "is_active": True, "order": 6
    }
]

FAQS_SEED = [
    {
        "id": str(uuid.uuid4()),
        "question_de": "Wie fr\u00fch muss man buchen?",
        "answer_de": "Wir empfehlen mindestens 4\u20138 Wochen im Voraus, bei grossen Festivals gerne fr\u00fcher. Kurzfristige Anfragen pr\u00fcfen wir ebenfalls gerne.",
        "question_en": "How far in advance should I book?",
        "answer_en": "We recommend at least 4-8 weeks in advance, for large festivals preferably earlier. We're also happy to review short-notice inquiries.",
        "question_fr": "Combien de temps \u00e0 l'avance faut-il r\u00e9server ?",
        "answer_fr": "Nous recommandons au moins 4 \u00e0 8 semaines \u00e0 l'avance, de pr\u00e9f\u00e9rence plus t\u00f4t pour les grands festivals. Nous examinons \u00e9galement volontiers les demandes de derni\u00e8re minute.",
        "question_it": "Con quanto anticipo bisogna prenotare?",
        "answer_it": "Consigliamo almeno 4-8 settimane di anticipo, preferibilmente di pi\u00f9 per i grandi festival. Esaminiamo volentieri anche le richieste dell'ultimo minuto.",
        "order": 1
    },
    {
        "id": str(uuid.uuid4()),
        "question_de": "Wie viele G\u00e4ste sind m\u00f6glich?",
        "answer_de": "Einzelne Trucks sind auf bis zu 300 G\u00e4ste/Stunde ausgelegt. Bei gr\u00f6sseren Events k\u00f6nnen mehrere Trucks gleichzeitig eingesetzt werden.",
        "question_en": "How many guests are possible?",
        "answer_en": "Individual trucks can serve up to 300 guests per hour. For larger events, multiple trucks can be deployed simultaneously.",
        "question_fr": "Combien d'invit\u00e9s sont possibles ?",
        "answer_fr": "Les trucks individuels peuvent servir jusqu'\u00e0 300 invit\u00e9s par heure. Pour les grands \u00e9v\u00e9nements, plusieurs trucks peuvent \u00eatre d\u00e9ploy\u00e9s simultan\u00e9ment.",
        "question_it": "Quanti ospiti sono possibili?",
        "answer_it": "I singoli truck possono servire fino a 300 ospiti all'ora. Per eventi pi\u00f9 grandi, pi\u00f9 truck possono essere utilizzati contemporaneamente.",
        "order": 2
    },
    {
        "id": str(uuid.uuid4()),
        "question_de": "Kommt ihr in die ganze Schweiz?",
        "answer_de": "Ja. Unser Heimgebiet ist Z\u00fcrich, Wetzikon und der Z\u00fcrcher Oberland, aber wir fahren f\u00fcr Events in die ganze Schweiz \u2013 je nach Aufwand mit Anfahrtspauschale.",
        "question_en": "Do you come to all of Switzerland?",
        "answer_en": "Yes. Our home area is Zurich, Wetzikon and the Zurich Oberland, but we travel across Switzerland for events \u2013 with a travel surcharge depending on distance.",
        "question_fr": "Venez-vous dans toute la Suisse ?",
        "answer_fr": "Oui. Notre zone d'origine est Zurich, Wetzikon et l'Oberland zurichois, mais nous nous d\u00e9pla\u00e7ons dans toute la Suisse pour les \u00e9v\u00e9nements \u2013 avec un forfait de d\u00e9placement selon la distance.",
        "question_it": "Venite in tutta la Svizzera?",
        "answer_it": "S\u00ec. La nostra zona di base \u00e8 Zurigo, Wetzikon e l'Oberland zurighese, ma ci spostiamo in tutta la Svizzera per eventi \u2013 con un supplemento di viaggio a seconda della distanza.",
        "order": 3
    },
    {
        "id": str(uuid.uuid4()),
        "question_de": "Braucht ihr Strom und Wasser?",
        "answer_de": "Je nach Truck unterschiedlich. Die genauen technischen Anforderungen geben wir euch nach der Anfrage mit den Unterlagen weiter.",
        "question_en": "Do you need power and water?",
        "answer_en": "It varies by truck. We'll provide detailed technical requirements with the documentation after your inquiry.",
        "question_fr": "Avez-vous besoin d'\u00e9lectricit\u00e9 et d'eau ?",
        "answer_fr": "Cela varie selon le truck. Nous vous communiquerons les exigences techniques d\u00e9taill\u00e9es avec la documentation apr\u00e8s votre demande.",
        "question_it": "Avete bisogno di corrente e acqua?",
        "answer_it": "Varia a seconda del truck. Vi comunicheremo i requisiti tecnici dettagliati con la documentazione dopo la vostra richiesta.",
        "order": 4
    },
    {
        "id": str(uuid.uuid4()),
        "question_de": "Gibt es vegetarische/vegane Optionen?",
        "answer_de": "Ja, bei allen Konzepten sind vegetarische Optionen verf\u00fcgbar. Vegane Anpassungen sind je nach Konzept m\u00f6glich \u2013 bitte beim Anfragen angeben.",
        "question_en": "Are there vegetarian/vegan options?",
        "answer_en": "Yes, vegetarian options are available with all concepts. Vegan adaptations are possible depending on the concept \u2013 please specify when inquiring.",
        "question_fr": "Y a-t-il des options v\u00e9g\u00e9tariennes/v\u00e9ganes ?",
        "answer_fr": "Oui, des options v\u00e9g\u00e9tariennes sont disponibles pour tous les concepts. Des adaptations v\u00e9ganes sont possibles selon le concept \u2013 veuillez le pr\u00e9ciser lors de votre demande.",
        "question_it": "Ci sono opzioni vegetariane/vegane?",
        "answer_it": "S\u00ec, opzioni vegetariane sono disponibili per tutti i concetti. Adattamenti vegani sono possibili a seconda del concetto \u2013 indicatelo nella vostra richiesta.",
        "order": 5
    },
    {
        "id": str(uuid.uuid4()),
        "question_de": "Was kostet ein Foodtruck-Einsatz?",
        "answer_de": "Der Preis h\u00e4ngt von G\u00e4stezahl, Ort, Einsatzdauer und Konzept ab. Wir kalkulieren individuell und senden euch eine transparente Offerte.",
        "question_en": "What does a food truck deployment cost?",
        "answer_en": "The price depends on guest count, location, duration, and concept. We calculate individually and send you a transparent offer.",
        "question_fr": "Combien co\u00fbte un d\u00e9ploiement de food truck ?",
        "answer_fr": "Le prix d\u00e9pend du nombre d'invit\u00e9s, du lieu, de la dur\u00e9e et du concept. Nous calculons individuellement et vous envoyons une offre transparente.",
        "question_it": "Quanto costa un impiego di food truck?",
        "answer_it": "Il prezzo dipende dal numero di ospiti, dal luogo, dalla durata e dal concetto. Calcoliamo individualmente e vi inviamo un'offerta trasparente.",
        "order": 6
    },
    {
        "id": str(uuid.uuid4()),
        "question_de": "Kann man mehrere Trucks buchen?",
        "answer_de": "Ja, genau das ist unsere St\u00e4rke. Ihr k\u00f6nnt mehrere Konzepte kombinieren und so f\u00fcr Abwechslung und k\u00fcrzere Wartezeiten sorgen.",
        "question_en": "Can I book multiple trucks?",
        "answer_en": "Yes, that's exactly our strength. You can combine multiple concepts to provide variety and shorter wait times.",
        "question_fr": "Peut-on r\u00e9server plusieurs trucks ?",
        "answer_fr": "Oui, c'est exactement notre force. Vous pouvez combiner plusieurs concepts pour offrir de la vari\u00e9t\u00e9 et des temps d'attente plus courts.",
        "question_it": "Si possono prenotare pi\u00f9 truck?",
        "answer_it": "S\u00ec, \u00e8 esattamente il nostro punto di forza. Potete combinare pi\u00f9 concetti per offrire variet\u00e0 e tempi di attesa pi\u00f9 brevi.",
        "order": 7
    },
    {
        "id": str(uuid.uuid4()),
        "question_de": "Was passiert bei schlechtem Wetter?",
        "answer_de": "Unsere Trucks sind grunds\u00e4tzlich wetterfest. Bei extremen Bedingungen besprechen wir gemeinsam Alternativen. Details regeln wir im Vertrag.",
        "question_en": "What happens in bad weather?",
        "answer_en": "Our trucks are generally weatherproof. In extreme conditions, we discuss alternatives together. Details are regulated in the contract.",
        "question_fr": "Que se passe-t-il en cas de mauvais temps ?",
        "answer_fr": "Nos trucks sont g\u00e9n\u00e9ralement r\u00e9sistants aux intemp\u00e9ries. En cas de conditions extr\u00eames, nous discutons ensemble des alternatives. Les d\u00e9tails sont r\u00e9gl\u00e9s dans le contrat.",
        "question_it": "Cosa succede con il brutto tempo?",
        "answer_it": "I nostri truck sono generalmente resistenti alle intemperie. In caso di condizioni estreme, discutiamo insieme delle alternative. I dettagli sono regolati nel contratto.",
        "order": 8
    }
]
